# Generated by Django 4.0.3 on 2022-04-22 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_quantity', models.PositiveIntegerField()),
                ('tickets_remaining', models.PositiveIntegerField()),
                ('ticket_nft_id', models.CharField(max_length=60)),
                ('title', models.CharField(default='EVENT TITLE', max_length=64)),
                ('description', models.TextField(default='EVENT DESCRIPTION')),
                ('images', models.JSONField(default=dict)),
                ('street_address', models.CharField(default='300 Circle Rd', max_length=60)),
                ('city', models.CharField(default='Stony Brook', max_length=10)),
                ('zipcode', models.CharField(default='11790', max_length=5)),
                ('state', models.CharField(default='New York', max_length=30)),
                ('date', models.DateField(default='2022-05-20')),
                ('time', models.TimeField(default='00:00:00')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('is_seller', models.BooleanField()),
                ('avtar_url', models.URLField()),
                ('wallet_addr', models.CharField(blank=True, max_length=100)),
                ('private_key', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_id', models.CharField(max_length=60)),
                ('is_expired', models.BooleanField()),
                ('on_sale', models.BooleanField()),
                ('price', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.user')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.user'),
        ),
    ]
