# Generated by Django 4.0.3 on 2022-04-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='private_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_addr',
            field=models.CharField(max_length=100),
        ),
    ]
