# Generated by Django 4.0.4 on 2022-04-26 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_event_event_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_sold', models.IntegerField()),
                ('date_sold', models.DateField(default='2000-01-01')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='server.user')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='server.user')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.ticket')),
            ],
        ),
    ]
