# Generated by Django 4.0.3 on 2022-04-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_event_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_nft_id',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='event',
            name='tickets_remaining',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
